### ISSUE TITLE
Folder InstallerFiles missing

### ISSUE THREAD

**Issue by zackmuc** [squid808/gShell#1]
Can you add the folder gShell-master\gshell\gshell\Installerfiles please

**Comment by squid808** [comment]
Hey zackmuc, I'm actually intentionally not providing that folder in the repository to prevent people from creating an installer that matches gShell's but is 'unofficial' - I hope you can understand why. I've included the installer code in the project for reference only, so that everyone can see what the installer is doing to their machine. 

If you're looking to compile and test things out on your own, I recommend using the most recent installer and then just rebuild the gShell project only. This will provide you with the .dll file that you can swap out in to the Module directory.

If you'd still like to compile everything including the installer, you'll need to supply the following files:
gShell.ico
gShell.psd1
gShellInstallerBackground.bmp
gShellInstallerTopBanner.bmp
gShellLicense.rtf
gShell.Format.ps1xml

Alternately, you can edit the installer project files to not include some of those, but the license and images are required by Wix (if I recall correctly).

Either way, I suggest just installing and then recompiling the .dll file. For rapid testing, I set myself up with a Symlink to the .dll file that is compiled and linked it to the Modules directory.

**Comment by zackmuc** [comment]
Ok Thx.
