### ISSUE TITLE
Export-GDriveFile issue

### ISSUE THREAD

**Issue by brice600** [squid808/gShell#17]
I've installed gShell Version 0.9.4 with MSI package on Windows Server 2012 R2 and I tried to export a Google Sheet Document into a csv file with cmdlet Export-GDriveFile.

I have no problem to retrieve properties from GDrive Documents (with Get-GDriveFile) but when I use Export-GDriveFile on a GDrive Documents : nothing happens (No error, no returned value, $? = "True")

Test : (From Spencer) (better than my own test :) )

**Import-Module gShell**

**$AllFiles = Get-GDriveFile -All
$Doc = $AllFiles | where {$_.MimeType -eq "application/vnd.google-apps.document"} | select -First 1
Export-GDriveFile -FileId $Doc.Id -MimeType "text/plain"**

**Comment by squid808** [comment]
Reproduced, I'll tackle this as soon as I can!

**Comment by squid808** [comment]
Hi Brice,

Please give it a shot with the newest version, 0.9.5 - Export-GDriveFile should now have a parameter for `-DownloadPath` where you can supply a full file path that will become the file in question. As per the Cmdlet help, see [this page](https://developers.google.com/drive/v3/web/manage-downloads) to determine what MIME type you'll need to use. Let me know if it works, and if it does I'll update the Wiki page!

Thanks!

**Comment by brice600** [comment]
Hi Spencer,

Thanks for all !

I have tried with the new version. Indeedn I have the new required parameter "DownloadPath" bit I have the same problem : No output, no file created, no error.

I have executed the same Test : 

**Import-Module gShell

$AllFiles = Get-GDriveFile -All
$Doc = $AllFiles | where {$_.MimeType -eq "application/vnd.google-apps.document"} | select -First 1
Export-GDriveFile -FileId $Doc.Id -MimeType "text/plain" -DownloadPath ".\doc.txt"**

**Comment by squid808** [comment]
Hey Brice, Thanks for getting back so quickly. It'ss odd that you're getting no error. The thing that sticks out here is that you're using the incomplete file path (`.\doc.txt`) which for me resolves to `C:\Windows\System32\WindowsPowerShell\v1.0\doc.txt`. I know this because if I'm not running PoSh under Administrator I get the following error:
`Export-GDriveFile : Access to the path 'C:\Windows\System32\WindowsPowerShell\v1.0\doc.txt' is 
denied.`

That happens even if I have set my working directory as my desktop:
`Set-Location $env:USERPROFILE\Desktop\`

So, with that in mind, if I instead use a fully qualified doc path (or anything that doesn't leave any ambiguity to PowerShell, like using the `$env` options), I have no problem getting the file.

Give this a try and let me know if it works (increase the max results or use the query parameter if you don't want to retrieve all of your documents which can take a while if you're like me):

`$AllFiles = Get-GDriveFile -All -MaxResults 50
$Doc = $AllFiles | where {$_.MimeType -eq "application/vnd.google-apps.document"} | select -First 1
Export-GDriveFile -FileId $Doc.Id -MimeType "text/plain" -DownloadPath "$env:USERPROFILE\Desktop\doc.txt"`

**Comment by brice600** [comment]
Hi Spencer,

It works ! 
I have done some tests with differents MimeType and it download correctly the file, I will be able to retrieve my data.

Thanks for your great job Spencer !

**Comment by squid808** [comment]
Hey Brice, thanks for letting me know! If you find anything else please let me know! Have a good one :)
