### ISSUE TITLE
Fresh install, config error

### ISSUE THREAD

**Issue by hitmany** [squid808/gShell#18]
Just installed this module and have issues with first init commands

Set-GShellSettings
Set-GShellSettings : "C:\Users\%D0%90%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0
%D1%82%D0%BE%D1%80\Documents\WindowsPowerShell\Modules\gShell\gShellSettings.config".

+  Set-GShellSettings
+  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-GShellSettings], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,gShell.Cmdlets.Utilities.gShellDomain.SetGShellSett
   ingsCommand

Windows Server 2012 r2 
$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

**Comment by hitmany** [comment]
FInally, its not working with cyrulic Profile folders
Pls fix)

**Comment by squid808** [comment]
Hi Hitmany,

What precisely are you trying to do? I'm having difficulty understanding how you are trying to use Set-GShellSettings from your example, I don't see any parameters included.

I briefly tested out cyrillic folders by creating a new folder named 'ћирилица' in my PowerShell modules folder, and then used the following command to set that as my default path for the config file:
```Set-GShellSettings -AuthInfoPath "$env:USERPROFILE\Documents\WindowsPowerShell\Modules\ћирилица"```

I then rebooted PowerShell and ran gShell and it had no problems seeing the file (running PoSh 4.0 and Win 10 - I don't have access to 2012 r2 at this time).

Please let me know how my test compares to what you were trying to do, and we'll see what we can figure out.

**Comment by hitmany** [comment]
Hello squid808, thank you for feedback and for great module!

I recieved this error on any **cyrillic user name,** when I type any gshell command
for example first time I typed get-qaduser, then I recieved System.IO.DirectoryNotFoundException

**Comment by squid808** [comment]
My pleasure! Sorry you've run in to an issue.

To be clear, you have a user in google already that has a cyrillic name, and you are unable to get gShell to work with it? Or you're pulling a user from AD that has a cyrillic name, and you're trying to pass that information through to gShell to create a new user or update a user?

I apologize for all the questions - I don't have any cyrillic names at my disposal to test with, so I need to know how you're using gShell so that I can try and reproduce the issue, so I can test it and fix it!

Thanks again.

**Comment by hitmany** [comment]
This happend with Windows cyrillic user name

**Comment by squid808** [comment]
Thank you, but I'm still unsure what to test with a username in Cyrillic - do cmdlets like Get-GAUser work? Last week when I used the cyrillic folder name in Set-gShell Settings, I had no issue. In your first comment, you said the issue was with ```Set-GShellSettings```, correct?

Can you give me a more detailed example that I can try to use to reproduce the issue?

For instance, you might say:
My windows username is [губерния](http://learn-cyrillic.ehpes.com/)
I'm trying to use the command ```Set-GShellSettings -SerializedFileType Json -AuthInfoPath "C:\Users\губерния\Documents\GShellSecrets\"```

**Comment by hitmany** [comment]
Okay, for example:

Create windows profile with username "губерния" and login in this account
Then try to use Set-gShellClientSecrets -ClientId "sfalskdhflaksdf23234-adsfpkasdgalskjdf.apps.googleusercontent.com" -ClientSecret "a235fbdosidhf3f8dSDfwefo"

**Comment by squid808** [comment]
Thanks for the information and your patience! I was able to recreate the issue and (I think) resolve it - head over to the [Downloads](https://github.com/squid808/gShell/wiki/Downloads) page and give 0.9.6.0 a try. I'll close out the issue as resolved, for now. Feel free to reopen if you find that it didn't work.

As an aside, for usernames like губерния that contain Cyrillic characters, if you already have a gShell_OAuth2.json or gShellSettings.config file in your gShell main directory, you may want to remove those and restart PowerShell to make sure no bad data was in them. Sorry about that!
