### ISSUE TITLE
Domain parameter not working as expected

### ISSUE THREAD

**Issue by squid808** [squid808/gShell#27]
Quoted from [here](https://github.com/squid808/gShell/issues/22#issuecomment-252976617) and split out to keep topics separate:

> Here is a list of things that do and don't work. 
> user.name1 primary email is domain1.com(primary) user.name2 primary email is domain2.com(secondary) 
> user.name3 primary email is domain2.com(secondary) with an alias for domain1.com(primary)
> Just for fun I made a user.name4 example, with primary email as domain3.com(tertiary), and alias of domain2.com
> using admin.user@domain1.com for authentication. domain1.com is set as default in oauth.
> 
> `Get-GAUser user.name1` - Works
> `Get-GAUser user.name1@domain1.com` - Works
> `Get-GAUser user.name1 domain1.com` - Works
> `Get-GAUser user.name1 -Domain domain1.com` - Works
> 
> `Get-GAUser user.name2` - 404 not found
> `Get-GAUser user.name2 domain2.com` - 404 not found (I expected this to request permission, but it didn't.)
> `Get-GAUser user.name2@domain2.com` - Works completely normally.
> `Get-GAUser user.name2 -Domain domain2.com` - Requests permission, Permission is given, 404 not found AND oauth not updated with new domain. I'm wondering if since I am trying to authenticate with the same account gshell doesn't create a new domain oauth for it. I then have to run authentication every single time I use one of the -domain options. 
> 
> `Get-GAUser user.name3` - Works
> `Get-GAUser user.name3@domain1.com` - Works
> `Get-GAUser user.name3@domain2.com` - Works
> `Get-GAUser user.name3 domain2.com` - Works
> `Get-GAUser user.name3 domain1.com` - Works
> `Get-GAUser user.name3 -Domain domain1.com` - Works
> `Get-GAUser user.name3 -Domain domain2.com` - Requests permission, Permission is given, works but oauth not updated.
> 
> `Get-GAUser user.name4` - 404 not found, everything is the same for this user as user.name2 except that user.name4@domain2.com and user.name@domain3.com both work. 
> ---
> 
> I don't really understand why this is happening. From all that testing I assumed the second parameter used as `mydomain.com` in your code example is only used to concatenate with the user provided in the first parameter(vs using it as the -domain switch as I thought before). I find this super weird, because it means that if you wanted to go into another primary GApps domain, it would look like: `Get-GAUser domain2.com -domain domain2.com`, which doesn't actually save any writing compared to using @domain2.com. BUT, if all it did was concatenate then why does `user.name2@domain2.com` work and `user.name2 domain2` doesn't? :confused:

**Comment by squid808** [comment]
@Allieway - To start, the original (way-back-when) use for -Domain was to set it in position 2 so that you could call ```Get-GAUser user domain.com``` and have the domain serve both as the domain for the user, and also to pull out the auth information. As time went on and the Cmdlet count increased, it became a default parameter to all Cmdlets in GShell to serve primarily as the Auth reference, but also as the Domain cmdlet if one such parameter exists for any given Cmdlet.

At this time, the proposition of splitting the Domain in to two cmdlets for those two specific uses would be a trying ordeal to determine which Cmdlets natively have a Domain parameter. Not impossible, but '_oh-my-god-I-don't-look-forward-to-that_' type annoying. Best-case scenario I would have to leverage the Discovery API and iterate through the API calls for each API to determine which calls have the parameter, and then work them back in to the Cmdlets. The main pain point there is re-numbering the parameter order, and updating the related wikis for all of those. A short-cut would be to leave it as a non-mandatory and non-numbered parameter where possible and leave it at the end, but in for a penny...

Regarding the domain stuffs you tried, the syntax for Get-GAUser in your examples is:
```Get-GAUser [-UserKey] <string> [[-CustomFieldMask] <string>] [[-Projection] {Basic | Custom | Full}] [[-View] {AdminView | DomainPublic}] [-Domain <string>] [<CommonParameters>]```

When you run this command: ```Get-GAUser user.name1``` the following happens:

1. Before the Cmdlet even runs (using the [preprocessing hook](https://msdn.microsoft.com/en-us/library/system.management.automation.cmdlet.beginprocessing(v=vs.85).aspx)), GShell checks to see if you supplied a domain. If you haven't supplied a domain, it will pull the default domain from the saved file. If you supplied a domain that doesn't have saved information, or there is no default domain, it will (should?) prompt you to authenticate. The end result should be that it has a domain value in hand when the Cmdlet starts it's main task. In this case, you didn't supply a domain, so _domain1.com_ is used.
2. GShell then needs to [determine what the full username is](https://github.com/squid808/gShell/blob/master/gShell/gShell/Cmdlets/Directory/Directory.cs#L7055). The APIs expect a full email address, so if you provide just a username, it [fills in the rest with the default domain](https://github.com/squid808/gShell/blob/master/gShell/gShell/Cmdlets/Utilities/OAuth2/OAuth2CmdletBase.cs#L287-L296). In this case, you didn't supply a full email address, so it changes the user in to _user.name1@domain1.com_.
3. Since you're not using the ```-All``` parameter, we don't run in to the _my_customer_ issue.
4. Everything else proceeds as normal.

In that scenario, everything makes sense, I hope - you need to give the API a full email address, you only gave it a username so we're filling in the domain from the default domain (which is one of the intended purposes of that, initially).

Now, this command also works ```Get-GAUser user.name1 domain1.com```:

You are right, the ```CustomFieldMask``` is the second parameter. Turns out, if you put something nonsensical in that parameter, it still works. You can see for yourself on the API's _[Try It!](https://developers.google.com/admin-sdk/directory/v1/reference/users/get?authuser=1)_ again. Even if you put a ```CustomFieldMask``` as 'scoobydoo' you'll have no issues. Thus, this is functionally the same command as the first.

These:
```Get-GAUser user.name1@domain1.com```
```Get-GAUser user.name2@domain2.com```
```Get-GAUser user.name3@domain1.com```
```Get-GAUser user.name3@domain2.com```
follow the same logic as above. However, since you supply the full email address, it doesn't need to supply the default domain. As long as you provide a valid email address _to which your authenticated account has access to read_ this should work. Since domain2.com is under domain1.com, and you are authenticated to read domain1.com and below, you can see both. Based on the other discussion and your examples, at least on a one-off basis, this would be the appropriate way to retrieve accounts from non-primary domains.

```Get-GAUser user.name2``` - functionally looking for user.name2@domain1.com, which doesn't exist.
```Get-GAUser user.name2 domain2.com``` - same as above, actually using ```CustomFieldMask``` and not really the domain, hence no request for authentication.
```Get-GAUser user.name3 -Domain domain2.com``` - Going with this one first, it prompts and works. It sounds like GShell is happily assuming that this is a primary domain, and sending you out to Google who doesn't balk at the request. But what is sent back pukes a bit, nothing is saved, and it reverts to your primary and default domain. Since user.name3 exists in domain1.com, it works.
```Get-GAUser user.name2 -Domain domain2.com``` - Same as previous, but this account doesn't exist in the default domain. I think by now we can agree that this is _not_ the best way to get non-primary accounts. I won't pretend to know what magic is happening inside the black box that is Google's authentication back-end, but it seems like this just confuses the crap out of GShell (probably just returns some error or a blank response that I'm not seeing bubble up). I can't think of any good way to have GShell know this type of information, so this may just have to be a _caveat_ to users of nested domain setups.

All the rest are some combination of the above, at this point.

So, based on your tests (thank you, very much! It helped clear things up for me!) we know the following:
1. GShell will (should) assume that any parameters who need a full email address will default to the default domain if one is not provided by the user.
2. ```CustomFieldMask``` doesn't make the API call puke if you put in wonky strings.
3. If you need to pull information from a non-primary domain, manually put in the full email address.
4. Supplying a domain in the ```-Domain``` parameter for a non-primary domain while authenticated to the primary domain makes things authenticate and puke a bit, then reverting back to the default domain after it is done puking.

I'll leave this open for now, we may want to come back to it as the conversation on the customer parameter develops. However, even if the name of the current ```-Domain``` parameter changes, this rules will likely still apply.

**Comment by squid808** [comment]
I've given this all some thought.

> Also I finally get it. Domain is both being used as a switch for authentication, and as a way to allow supplying the user without domain name by combining the two(and using the default domain). I have only ever supplied the full email as that's what I was used to, and didn't realize you had set it up to work that way. That does make a ton of sense and is actually quite a smart way to do things if google apps domains worked the way you had thought. The reason I never ran into the issue before was because I didn't supply domain name until it was required(Get-GAUser -list). Damn, this makes the whole problem a lot more complicated.

To comment on this, I'm still considering my options. I see the value in what you say, it's just down to how will I be handling any kind of changes or implementations. If I could start all over again, I'd certainly not have combined the uses of ```Domain``` in to a single parameter, and I'd go so far as to say it was foolish to do so, but at that time GShell was nothing more than a personal project I was hosting on Google Code.

I'm willing to make breaking changes up until I make a release of version 1, but I want to make sure I make changes like that only once. Right now I'm playing with an idea of changing the Auth use of domain in to a separate, ubiquitous parameter of something like ```-GAuthId``` and allowing it to be either a username or a domain (or a full email if they wanted). So, all of the following would potentially work:

```Get-GAUser someuser``` - would look for a default domain, find it, and then find the default auth user. Similar to how it currently stands - prompting for authentication if either are missing.
```Get-GAUser someuser -GAuthId myAdminUser``` - would scan the auth file to see if myAdminUser is a domain. It is not, so check the default domain (prompt for authentication if missing) and see if that user is authenticated for it. If not, prompt for authentication.
```Get-GAUser someuser -GAuthId myAdminUser@domain.com``` - would see that both a user and domain are provided. Would check the file and if either are missing, would prompt for authentication.
```Get-GAUser someuser -GAuthId domain.com``` - would scan the auth file to see if domain.com is a domain. If missing, prompt for authentication. If present, since no user is provided it checks for a default user for that domain. If sees none, prompts for authentication.

In this case, we're still relying on the similar structure of having the top level of domains, below that users and below that APIs, since that's always going to be the case. We're still assuming that the user can not include something and ergo we have a default domain and for each domain a default user. But, by expanding the use of the parameter to be either a domain or a user (or both at once in an email), we might be able to better fit the use cases you've provided.

If you are using GShell in some application where you can't be sure that the user wouldn't be ambigous between two primary domains, or that you can't be sure that it's in the default domain, you would be able to just always provide GShell with the full email address and it would handle keeping track of it for you.

This wouldn't save me from having to restore the ```-Domain``` parameter, but so be it. As you said elsewhere, chances are most people aren't even using it for that most of the time, and it'd be best to ensure that all API parameters are appropriately represented only for their purposes in GShell - not some GShell bastardization thereof.

In a scenario where GShell starts keeping track of many, many users - it may be time to take a step back and consider if the basis for the project might better be served by something like a database and the C#/.Net client libraries, or a fork of GShell to use a database instead of a .json or .bin file.

Thoughts on that?

**Comment by Allieway** [comment]
> So, based on your tests ... we know the following...

All of that makes sense now. I think the main thing was the readme using the old method for Domain being second parameter is what confused me the most. 

> GShell then needs to determine what the full username is. The APIs expect a full email address, so if you provide just a username, it fills in the rest with the default domain. 

The second link is what I was looking for when I was going through code, I didn't know where it was located, although I sure did see enough calls for GetFullEmailAddress to connect the dots.

___

So you are saying getting rid of `-Domain` and using `-GAuthId` instead? 
Would calling `Get-GAUser someuser -GAuthId domain.com` Still create the full email by combining GAuthId(if it's detected as a domain, and if it's not detected as an domain, uses the domain for the user authed, and if not provided, uses the domain of the default domain)? 

I have an idea, bare with me here for a moment, not sure if this is really good or not. 

I was thinking it all through and your idea seems to cover almost all use cases. However I was considering how the service account is setup, and the fact it is tied to a specific domain. Since you want to keep domain as a way of authenticating why not use the full email address provided as a way to change who the auth user is? Then have a primary domain with secondary domains listed underneath. This is confusing, let me draw it out.

1. On first auth: Assume domain is primary and list it as primary in oauth file.

If user authenticates admin.directory.domain or admin.directory.domain.readonly have gshell automatically run a -list on the domain, organize the oauth file with parent domain and all extra domains. 

Also have a gshell cmdlet for Getting an authed users list of extra domains, in case they had not authenticated with admin.directory.domain yet, but still would like to list domains in oauth. 

Place service account under primary domain, not under each domain specifically. 

Instead of having a default user for each domain, have a default primary domain user, and a default secondary domain user. 

So oauth file would look like this(I'm going to seperate users and domains for readability, you can throw them inside if you wanted to as it is currently):

```JSON
{
  "domains": {
    "primarydomain.com": {
      "secondarydomains": {
        "secondarydomain.com": {
          "default_user": {
            
          }
        },
        "anothersecondarydomain.com": {
          "default_user": {
            "user@secondarydomain.com"
          }
        }      
      },
      "users": [
        "user@primarydomain.com",
        "user@secondarydomain.com"
      ],
      "default_user": "user@primarydomain.com",
      "serviceAccountEmail": "blahblah@blah.com",
      "jsonCertificate": "-----BEGIN PRIVATE KEY-----"
    },
    "anotherprimarydomain.com": {
      "secondarydomains": {},
      "users": ["user@anotherprimarydomain.com"],
      "default_user": "user@anotherprimarydomain.com"
    }
  },
  "defaultDomain": "primarydomain.com",
  "clientSecrets": {
    "client_id": ".apps.googleusercontent.com",
    "client_secret": ""
  },
  "users": {
    "user@primarydomain.com": {
      "tokenAndScopes": {}
    },
    "user@secondarydomain.com": {
      "tokenAndScopes": {}
    },
    "user@anotherprimarydomain.com": {
      "tokenAndScopes": {}
    }
  }
}
```

Here are some examples for how it would work functionally:

`Get-GAUser someuser@primarydomain.com` - Would extract primarydomain.com from the string, and check for matching domains, if a domain is matching, use the default_user for the domain.
`Get-GAUser someuser@secondarydomain.com` - Same as above, but it finds that it matches a secondary domain. The secondary domain has no default user, so it uses the primary domains default user.
`Get-GAUser someuser@anothersecondarydomain.com` - This time it matches a secondary domain that does have a default user. It uses this user instead of the primary domains default user. By default secondary domains woudn't have default users, and any user added to a secondary domain in gshell would just be added to the user list of the primary domain, but not set as default unless specified. You can set any user listed under the primary domains user list as a default user for the secondary domain. 
`Get-GAUser someuser@anotherprimarydomain.com` - Finds matching primary domain, uses default user for that primary domain.
`Get-GAUser someuser@notlisted.com` - Domain not found in oauth, so gshell uses default domain, and default user. Maybe you could spit out a non terminating error that gives the option to run the command that adds secondary domains, as gshell thinks this user isn't going to be found(Which it won't be found if the user has already added secondary domains). 

Now someone can use any email address the same exact way they did before, but with much smarter auth choosing. Let's move on to adding GAuthId, then do service accounts last.

`Get-GAUser someuser@primarydomain.com -GAuthId secondarydomain.com` - Gshell detects GAuthId was used, so we no longer parse auth by email address. It checks secondarydomain.com, sees doesn't have a default user, uses primarydomain.com's default user. 

The rest of GAuthId would work the exact same way you wrote about, simply ignoring a full email given when it's supplied for authing purposes, but still using it for API purposes. The only difference is the above example that incorporates primary domain's default users as well. 

Now for the part that I really like, and the main reason I like this method of doing things - Service accounts(Please note I am using a toggle for service account like I recommended in one of the previous posts, it would work the exact same way with current syntax):

`Get-GGmailMessage someuser@primarydomain.com -All` - Service account not specified, uses default user and tries to get message with delegation. 
`Get-GGmailMessage someuser@primarydomain.com -All -ServiceAccount` - checks primary domain for service account, it's found, and runs correctly.
`Get-GGmailMessage someuser@secondarydomain.com -All -ServiceAccount` - This is the main reason I didn't like the domain method, with gshell thinking secondarydomain.com is a seperate domain it would fail as the service account wasn't added to that domain. 
`Get-GGmailMessage someuser@anotherprimarydomain.com -All -ServiceAccount`- Spits an error that anotherprimarydomain.com does not have a service account setup. 
`Get-GGmailMessage someuser@notlisted.com -All -ServiceAccount` - Defaults to primary domain, Giving the same recommendation to the user as the Get-GAUser notlisted.com, as gshell doesn't think it will be found.

I really like the idea of users not having to specify a -Domain or a -GAuthId for gshell to route authentications correctly. From what I can tell this would be extendable to any possible use case in the future and work well with all of the API's without interference, and wouldn't be too hard to implement as Gshell already checks if the domain is supplied with the user, so it would just take the domain and change auth user based on it. This would also make scripting extremely consistent between users, because no matter how complex someones authentication is, they would use the same exact code as someone else, by using a full email address. This makes it so I wouldn't have to go in and add a bunch of GAuthId options to someone elses script to test it, and also I wouldn't have to redesign scripts if I ended up increases amount of auth users or domains in general over time. 

Let me know what you think on that, if it all makes sense, or if you have any questions. 

___

> In a scenario where GShell starts keeping track of many, many users - it may be time to take a step back and consider if the basis for the project might better be served by something like a database and the C#/.Net client libraries, or a fork of GShell to use a database instead of a .json or .bin file.

I think that makes a lot of sense for my over eagerness towards using multiple users. I do think gshell itself should be able to handle ~10 users perfectly fine, and json won't become a huge bottleneck until much, much further than that. 

However, if we are talking 100+ users and usable by many different people, It would be a great idea to use the base C#/.Net client libraries with a database, or a fork of GShell using databases as well. I assume you recommend that based on my mentioning a web front end. It sounds fantastic, and would be a very fun project, possibly making it usable by the masses instead of just for developers or scripters. For my personal use I think it makes more sense to stick with powershell, as most of the time I'm incorporating GShell into other scripts that are pre existing. My web project is still very WIP, I'll let you know more when I know more. :stuck_out_tongue: 

Also I'm sure I'll head over to the google groups at some point, This is quite a strange use of github issues, but thanks for carrying on before I make my way over.

**Comment by squid808** [comment]
I need to make sure again that I understand the behavior of the secondary domains.

1) If you have an admin account in secondarydomain.com that you need to use, maybe to allow some technician to perform specific admin tasks on just that secondary domain, and they wanted to use GShell - if they installed GShell fresh, added the client ID and secret, authenticated against that admin account and called ```Get-GAUser someuser@secondarydomain.com``` - what would happen (assuming they don't specify ```-Domain secondarydomain.com```?

I've reviewed the code and what happens when you authenticate is GShell actually discards any ```-Domain``` information you may have provided (since who knows, you could have gotten it wrong or made a typo) and instead takes the [returned authentication information](https://github.com/squid808/gShell/blob/master/gShell/gShell/dotNet/Utilities/OAuth2/OAuth2Base.cs#L53) (which only has a User ID) and uses that to [pull your profile information](https://github.com/squid808/gShell/blob/master/gShell/gShell/dotNet/Utilities/OAuth2/OAuth2Base.cs#L135-L137). (That's why there is that extra scope in every API you authorize - it makes absolutely sure your information is accurate.)

Based on that, I'm wondering what Google returns in a secondary domain scenario - I'm assuming it gives the secondary domain, but is that what goes in to the OAuth file? Do the GShell calls work after that? Can you test this out and let me know?

2) How do service accounts work for secondary domains? My assumption is you have to add it in the CPanel for each domain you want it to have access to, correct?

3) In the JSON output you put together, can you remind me why we need to keep track of auth accounts for secondary domains?

---

> Since you want to keep domain as a way of authenticating why not use the full email address provided as a way to change who the auth user is? Then have a primary domain with secondary domains listed underneath.

This makes sense, but I don't know if it's feasible or not with the current overall design. Each Cmdlet that deals directly with the API [inherits from a respective base class](https://github.com/squid808/gShell/blob/master/gShell/gShell/Cmdlets/Directory/Directory.cs#L6894). This base (and abstract) class is where the [preprocessing methods are defined](https://github.com/squid808/gShell/blob/master/gShell/gShell/dotNet/Directory/Google.Apis.admin.Directory.directory_v1_gshell_dotnet.cs#L155-L171) for that entire API set. The problem with this is that this abstract base class is only aware of the [parameters that it defines](https://github.com/squid808/gShell/blob/master/gShell/gShell/dotNet/Directory/Google.Apis.admin.Directory.directory_v1_gshell_dotnet.cs#L49-L54) - not any of the parameters which the child classes define.

So, think of it this way - the authentication pieces take place before the Cmdlet is fully aware of the rest of its unique parameters like UserName. Thus, tying in the parameters that exist on the individual Cmdlet level, like UserName, would have to happen _after_ the authentication takes place, unless of course we go through for every Cmdlet and override the ```BeginProcessing``` method (which I have no intention of doing).

This is the primary reason why we have to use a separate parameter to identify the authentication set we're using, since it has to apply to all of the Cmdlets for each API. That brings us back to the scenario of some parameter like (the name I made up on the spot of) ```GAuthId```.

The only way I can see around this is by overriding ```BeginProcessing``` on each individual Cmdlet so that the parameter set(s) for that Cmdlet can be custom tailored to integrate with the authentication. A handful of helper functions could assist in this, as could an intermediate layer of abstract classes that override the aforementioned function and declare the parameter, though you would have to make absolutely sure that all Cmdlets inheriting from that declare the parameter in exactly the same way, I think, unless you try overriding the property at which point that can [get ugly](http://stackoverflow.com/questions/326223/overriding-fields-or-properties-in-subclasses).

Then you'd have to consider doing this for any and all Cmdlets that offer some type of email address or object ID that could be involved in such a behavior, and you'd also have to decide how to handle scenarios like ```Get-GAGroupMember -GroupName $G -Member $M``` - do you use the group or the member's information, or if both in what order of importance?

My point is, I think it gets unreasonably hairy and convoluted for the back-end of things, when a seemingly simple answer is already right in front of us. At the point where the user is running in to scenarios where this becomes an issue, I'll be happy to help out via the discussion group on ideas of how to structure such a Cmdlet where they're running in to this.

---

Ultimately, I would say this:

1) Making the change for the ubiquitous parameter of ```Domain``` to something else holds merit and will need to be considered further. The time-consuming part will likely being the updating of any Cmdlets with the ```Domain``` parameter natively, and the updating of the wiki.
2) I don't think I'll be pursuing the idea of integrating the username / groupname / othername parameters with the for-now-named ```Domain``` parameter, since that gets us in a wholly different mess, as far as I can see it.
3) The suggestion for making the service account could be further investigated, but it's going to run in to the same issues as integrating the usernames etc to the ```Domain``` parameter, since it [also uses ```BeginProcessing```](https://github.com/squid808/gShell/blob/master/gShell/gShell/Cmdlets/Drive/Drive.cs#L16-L30). If you can find an elegant way out of that which wouldn't involve me touching and customizing all of the affected Cmdlets, I'm open to suggestions!

**Comment by Allieway** [comment]
In response to your first section:

1) Same exact thing that happens now. They would authenticate for the first time, gshell would fill out domain as normal in oauth, then fetch the user.  Yes it gives secondary domain, yep gshell works fine after that. Since you stated before that the oauth domain organization is just what gShell uses, and the secondary domain user is an admin of the primary domain. There is only one domain, 1 thing to authenticate to. As I said previously google does not differentiate between them AT ALL. The use case for having a secondary domain built into gshell would be if a super administrator is part of that secondary and not primary, or if you have multiple users under different secondary domains, and would like to authenticate with different ones depending on which domain is called. It's fundamentally the same as the current setup, just handles service accounts better, and would work well with my proposed scenario of authentication in the second section.

2) Everything is under the umbrella of the primary, and every secondary user has access to everything a primary user has(see 4 for the only exception I know of), and every change made in the interface is made to the only domain that exists, primary. Basically: One service account for one domain.

3) This was mainly for keeping in mind 3 things. 1. Service accounts do not need to be authenticated differently for secondary domains, so I wanted to lump secondary domains in with the primary domain, as a way to keep the service account linked. 2. Since you wanted to keep the option for gShell to choose authentication based on domain and not just per user, I wanted to have the option to set a default user per secondary domain, in the off chance someone would prefer to use a different account when the secondary domain is called. 3. If we were to do automatic authentication based on the full user email provided, this would be the best way to automatically always choose the correct authentication. It would automatically choose the correct service account, or user, and allow the gShell user to set precise per domain users. 

4) As I said previously, just trying to get every use case possible and handle it automatically for ease of scripting. 
During my thoughts I had this idea:

You can restrict permissions by organization, which is different than Domain. This could technically be used to separate permissions by domain, giving a user admin permission to only the organizations that happen to have certain domains for example. So I could have 1 primary domain in gshell, with 3 different users each having 3 organizations of permissions, and setting them as default users for the respective domains. 

Another would be a gshell user simply wanting to use a different account for different users called. Maybe they aren't using a service account, but have accounts with delegation over others. When a specific secondary domain is called, they would want the default user that has delegation over those users to be used. 

If I end up writing 2,000 lines of a gshell script, and end up having a change in the way administration works, I would need to rewrite alot of my code. With all the setup being done in the authentication with default users, Someone should be able to make simple adjustments in the config and not have to modify scripts at all. This obviously was based off of tying into the second section with full email authentication tied in. 

___

Gotcha. That makes a lot of sense.

Rechecking authentication at the same time as `GetFullEmailAddress` would cause issues with gShell checking scopes, asking the user to update scopes, then changing who the cmdlet is authenticating with and possibly running into the same issue again.  Then as you said you have to add on situations like groupname and member. Hmm, alright. Seems rather reasonable to not go through the hassle then. 

___

> If you can find an elegant way out of that which wouldn't involve me touching and customizing all of the affected Cmdlets, I'm open to suggestions!

I think this is the basis behind all of the recommendations that are affected by `BeginProcessing`. I didn't realize that is the way it worked, thus increasing the amount of work it would be to incorporate. 

I still vote for changing of the `Domain` to include authenticating by email address/user name. I believe that would solve almost all issues I wanted to anyway. The only leftover thing would be service accounts, and if they are tied to a user or a domain, and how they are called in a multi user environment.

**Comment by squid808** [comment]
I'm splitting out the conversation about the structure of the Auth file for subdomains [here](https://github.com/squid808/gShell/issues/29).

I'm already working on fixing the ```-Domain``` bit, splitting that out in to ```-Domain``` and ```-GAuthId``` and handling the transition for that, so no worries there. The good news is many cmdlets may be fine without the -Domain cmdlets, for instance [```Get-GAUser```](https://developers.google.com/admin-sdk/directory/v1/reference/users/get), which is based on an API call that doesn't actually ask for the domain. So, that's neat. We'll see if that's a trend or an exception.

Task list for my reference, as it currently stands:

1. Change the ubiquitous parameter from -Domain to -GAuthId
2. Identify which cmdlets natively support a -Domain parameter, and fix them. (May best be handled via json output from Discovery API - use to gather and format to copy and paste?)
3. Update related wiki docs as we go.
4. Add in logic for the GAuthId interpretation to check if it is a username, email or domain before sending it off to authenticate. Check for domains first.

Did I miss anything? I apologize, but do keep in mind that this all takes place at the point in the day where I'm somewhat falling asleep :)

**Comment by Allieway** [comment]
Looks good, doesn't look like you missed anything. And I know, you often reply when I'm already out for the night(or far too tired to reply at that time)! :P 

Feel free to ask for help with anything. Just give me some instruction of where you need assistance and I'm happy to help. 3. That goes for updating documentation or anything else. 

2. I'm not super familiar with Discovery API, if you think that would work well then great! However, I kinda think it's only the directory API, and inside of that only list for Groups and Users(-All). I don't think anything else has the option to use -Domain. Since it's just a filter it would only be on a list, and I went through every list in directory api and those 2 were the only ones. 

4. currently if you input anything into -Domain it will take it and try to auth with it. I would say if it's not in domain format, or not in email format, then gShell would think it's a username(right?). If the username wasn't found I think it would be better to spit a non terminating error than ask for authentication so as not to interrupt scripts that are given incorrect information. 

I guess people could make typos and still want to authenticate, maybe a timer to default to the default domain if y or n aren't specified? Doesn't really matter that much though I guess. 

Thanks for all your hard work :)

**Comment by squid808** [comment]
I'm going to move point 4 above:

> Add in logic for the GAuthId interpretation to check if it is a username, email or domain before sending it off to authenticate. Check for domains first.

...to issue #29 since it has more to do with the relationship between the authentication and the saved auth file. That said, the rest mentioned here is [I think] resolved and will appear in the next release.

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
