### ISSUE TITLE
Get-GAGroupMember -All returns 400 Bad Request error

### ISSUE THREAD

**Issue by Allieway** [squid808/gShell#30]
I didn't realize gShell advertised this as a working option, as it's not how the google API works. 
Is this still supposed to work, or are you supposed to pipe results of both `GetGAGroup -All` and `Get-GAGroupMember $Group` as I have been doing it this way, and you mentioned it [here](https://groups.google.com/forum/#!topic/gshell-discuss/9ZQHC-wQwxw).

https://github.com/squid808/gShell/wiki/Get-GAGroupMember#allgroups

**Comment by squid808** [comment]
Ok yeah, when I first started this project I had tried to include 'convenience' methods and parameters (keeping in mind this started as a personal project based on making my frequent tasks easier) - this being one of them, which basically just replaces a decent little foreach loop or a good pipeline by doing that for you under the hood, which [clearly] broke.

I'm trying to clean gShell up and adhere much closer to what Google is giving us directly. I'll remove this, I think, so no more -All param for the GetGAGroupMember. Piping in GShell is something I may have to revisit down the line, I've honestly not been giving it much thought up until this point since using variables and parens hasn't been _that_ much of an inconvenience up until now. That could be a good side project down the line if you or anyone else is interested!

Since I'm removing this in the next release, I'll close this out at that time. Sorry if you were planning to rely upon that param!

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
