### ISSUE TITLE
Powershell Version

### ISSUE THREAD

**Issue by willpolley** [squid808/gShell#36]
This is just a general question.

For this project, are there any significant advantages of using PS4 over PS3?

I'm sure there are. I just don't know enough about the versions to be honest.

The reason I'm asking is that I was trying to integrate gShell into our AD app called Adaxes. They're currently only looking to support v3 in the near future. Sad trombone. I only found that out after a few afternoons of scripting a groups management action. Sad panda.

Thanks for this great project.

**Comment by squid808** [comment]
My pleasure, I'm glad you are finding use of it! And, sorry for the delayed response. To my knowledge, no - there would be no significant benefit to using 4 over 3. The project itself is built targeting .Net 4.5.1 (in part to support the underlying project dependencies), so as per [here](https://msdn.microsoft.com/en-us/powershell/scripting/setup/windows-powershell-system-requirements) gShell may need a higher version of .Net than PoSh 3 does (4.5.1 vs 4, respectively) assuming I'm reading that right.

That said, once you install gShell locate the gShell.psd1 file in your installation directory, and tweak the following lines as needed, leave them blank or just delete the whole file I suppose:
```
# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.5.1'
```

That should loosen up the restrictions on the version. It's been a while since I've messed with that kind of stuff, but let me know if it works. 👍 

Also, keep in mind you might be able to find more response from other users on the [gShell Discussion Group](https://github.com/squid808/gShell/wiki/Discussion-Groups), or if it's generic enough you could try any of the various online PoSh communities, like [Reddit's /r/PowerShell](https://www.reddit.com/r/PowerShell/) or the [microsoft.public.windows.powershell Google Group](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/microsoft.public.windows.powershell/topics).
