### ISSUE TITLE
Get-GAuserphoto does not return no photo for user without Photo

### ISSUE THREAD

**Issue by coolsammy** [squid808/gShell#44]
Get-GAuserphoto does not return "no photo for 'user's email address'" instead it throws an error.

_Get-GAUserPhoto : Google.Apis.Requests.RequestError
Resource Not Found: photo [404]
Errors [
    Message[Resource Not Found: photo] Location[ - ] Reason[notFound] Domain[global]_

**Comment by squid808** [comment]
Gshell isn't set up to return custom errors for each cmdlet, instead it simply passes through any errors that Google provides in order to provide you, the user, with all the error information that Google would normally give you (to help troubleshoot it). Rather than gShell deciding exactly how you should handle your errors, the decision is left up to you in case you prefer to handle it in some other way.

In this case, you could wrap it in a try/catch something like this:
```
try {
    Get-GAUserPhoto myuserhere -ErrorAction Stop
} catch [Google.GoogleApiException] {
    Write-Warning ("No photo found for user {0}" -f $_.CategoryInfo.TargetName)
} catch {
    #...handle any other errors
}
```

If you don't want to see the error, you could instead use ```-ErrorAction SilentlyContinue``` which would suppress the error altogether.
