### ISSUE TITLE
Get-GCalendarEvent - Can't list all events in a calendar

### ISSUE THREAD

**Issue by djdasubz** [squid808/gShell#46]
Hi There,

When I go to use `Get-GClandarEvent -CalendarID XYZABC@domain.com -All` it fails.

The Wiki Example 2 = `PS C:\> Get-GCalendarEvent -CalendarId $SomeCalendarIdString -All`

Ideally I would like to be able to list all events in a calendar. I would then use this information + a separate list of users, to invite users to their events. After look at the Wiki Page, "-EventID" is a require parameter which would void the Example 2?

I understand this is a big project and very much appreciate all the work you and the volunteers do to keep this project active. Thank you for any assistance or help you may be able to provide!

Cheers,

---------------------------- Powershell Error Dump ----------------------------------------

```
Get-GCalendarEvent : A parameter cannot be found that matches parameter name 'All'.
At line:1 char:99
+ ... s.school.nz_eqfg2chracqu0u1uer5e4glpjk@group.calendar.google.com -All
    + CategoryInfo          : InvalidArgument: (:) [Get-GCalendarEvent], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,gShell.Cmdlets.Calendar.Events.GetGCalendarEventCommand
```

**Comment by squid808** [comment]
Turns out there should have been an `-All` parameter, but for whatever reason I forgot it. Added, tested, seems to work. You can compile the result get a few more issues resolved I'll throw out a new installer and subversion. Sorry about that!

In the meantime, you can use any of the other parameters in that same parameter set to trigger it:
`PS C:\> Get-GCalendarEvent -CalendarId $SomeCalendarIdString -MaxResults 2500`

Since `MaxResults` is only available in the parameter set that gives more than one result (the same set that `-All` uses) it will get you what you're looking for.

**Comment by djdasubz** [comment]
Thank you! That worked perfectly!
