### ISSUE TITLE
Help: Setting Drive Permission

### ISSUE THREAD

**Issue by k0d3r3d** [squid808/gShell#54]
Hoping to have this figured out before a meeting I have a 1:30  :) cant seem to figure it out :( help would be greatly appreciated. 

Question originally posted : https://groups.google.com/forum/#!topic/gshell-discuss/z67AjvLhSxc

Im sure its something stupidly simple, but I've resorted to trying to figure out the json format to put it into  a variable for the -permissionbody tag but nothing works. 
![image](https://cloud.githubusercontent.com/assets/20447286/25137543/0fa0b03a-2426-11e7-9dc6-854020156c2a.png)

**Comment by squid808** [comment]
When you see an argument with a name of something*_body_, you can be pretty sure there is another cmdlets that creates that object. Reason being - Google's APIs are object oriented, like gShell, and I've decided to keep that structure intact. This allows you to create and pass along multiple objects where permitted, but it does require a little more coding on our end. Luckily we can easily create functions and cmdlets to work around that. :)

So, step 1 is to get a handle on the file. When working in Google Drive, I recommend using [service accounts](https://github.com/squid808/gShell/wiki/Service-Accounts) since that will allow you to impersonate the user in case you don't have access as the admin.

For my example, I'll first set up three variables to represent my users and the domain. You'll need to add the new user as their full email address, since this can be done outside your domain as well (it could be a gmail account, for example):

```
$User = "oldowneraccount" #the old owner username
$Domain = "yourdomain.com" #your domain that $user is in
$NewUser = "newowner@yourdomain.com" #the new owner's full email regardless of domain
```
**Note: You can omit the `$Domain` variable for the `-GAuthId` param if you're going to be working within the same, default domain that you have set up for gShell**

If we assume you have a handle on the file in a variable $File, you should be able to get the file ID from that as well. I'll just get a list of all items from that user and pick the first one:

```
$File = (Get-GDriveFile -All -TargetUserEmail $User -GAuthId $Domain)[0]
```
Now that we have the file, let's create a new permissions object. We'll supply this as part of another cmdlet shortly. Role and type are [required](https://developers.google.com/drive/v3/reference/permissions/create) - so is the email of the user (the full email address, regardless of domain) if you're adding a user.

```
#
$Body = New-GDrivePermissionObj -EmailAddress $NewUser -Role owner -Type user
```
Now we have the body object set up, we can pass it along to Google.
**Note: `-SendNotificationEmail` can't be set to `$false` when changing owner!**

```
New-GDrivePermission -FileId $File.Id -PermissionBody $Body -TargetUserEmail $User `
    -GAuthId $Domain -TransferOwnership $true
```

Now that we have that done, let's check out the permissions one last time to see if it worked. I've included the StandardQueryParams as all (using the asterisk) so that I get back all the info about the results.
```
$Perms = Get-GDrivePermission -FileId $File.Id -All -TargetUserEmail $User `
    -GAuthId $Domain -StandardQueryParams (New-GShellStandardQueryParametersObj "*")
```

Again, this will require that a service account is set up to work, but once you get that done you should be all set. Let me know if you have any other questions!
